"""Subclass of ClientFrame, which is generated by wxFormBuilder."""

import wx;
import ClientChatGUI;
import ClientChat;

# Implementing ClientFrame
class ChatClientClientFrame( ClientChatGUI.ClientFrame ):
        def __init__( self, parent ):
                ClientChatGUI.ClientFrame.__init__( self, parent )
                self.client = ClientChat.ClientChat()	# Handlers for ClientFrame events.
        def OnClientConnectServer( self, event ):
                # TODO: Implement OnClientConnectServer
                self.client.clientConnect(self.m_ServerHostText.GetValue(), int(self.m_ServerPortText.GetValue()), lambda x : self.OnClientReceiveMessage(x))
                pass
        def OnClientChatSubmit( self, event ):
                # TODO: Implement OnClientChatSubmit
                if len(self.m_ClientChatText.GetValue()) > 0:
                       self.client.sendMessage(self.m_ClientChatText.GetValue())
                       self.m_ClientChatText.SetValue('')
                pass
        def OnClientReceiveMessage(self, message):
                print (message)
                prevertMessage = self.m_ChatReceiverText.GetLabel()
                self.m_ChatReceiverText.SetLabel(prevertMessage + '\n' + message)
                pass
	
if __name__ == '__main__':
        app = wx.App()
        window = ChatClientClientFrame(None)

        window.Show(True)
        app.MainLoop()



